sudo: false
language: node_js
node_js:
  - "8.9.3"
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: output
  on:
    branch: master
